"""MediBot, scripted version.

Detailed, structured first-aid and flood-health guidance, matched by keywords in English, Hindi,
Marathi and common romanised words. `reply()` keeps the shape an LLM-backed version will use, so
the app does not change when you upgrade.

Content follows Indian Red Cross / St John Ambulance first-aid manuals, WHO flood-health guidance
and NDMA advisories. It is general guidance, not a diagnosis; every serious topic points to 108 / 112.
"""
import re

DISCLAIMER = "General first-aid guidance, not a diagnosis. In an emergency call 108 (ambulance) or 112."

# urgency: "emergency" (call now), "urgent" (see a doctor today), "care" (self-care, watch for signs)
TOPICS = [
    {
        "id": "cpr", "urgency": "emergency", "call": ["108", "112"],
        "keywords": ["cpr", "not breathing", "no breathing", "unconscious", "drown", "drowning", "collapsed",
                     "no pulse", "doobna", "doob", "saans nahi", "behosh", "बेहोश", "डूब", "श्वास", "सांस", "बुडाला"],
        "title": "Drowning or not breathing",
        "summary": "Every second counts. Get help coming, then start CPR if the person is not breathing normally.",
        "steps": [
            "Shout for help and call 108 or 112. Put the phone on speaker so the operator can guide you.",
            "Only go into water if it is safe. Reach with a pole, rope or cloth, or throw something that floats.",
            "Lay the person on their back on firm ground. Tap their shoulders and shout: do they respond?",
            "Tilt the head back, lift the chin, and look for normal breathing for up to 10 seconds. Gasping is NOT normal breathing.",
            "Drowning: give 5 rescue breaths first. Pinch the nose, seal your mouth over theirs, blow for 1 second until the chest rises.",
            "Then CPR: heel of one hand in the centre of the chest, other hand on top. Push down 5 to 6 cm, 100 to 120 times a minute (the beat of 'Stayin' Alive').",
            "Give 30 pushes, then 2 breaths. If you can't or won't give breaths, keep pushing without stopping.",
            "Children: use one hand (or two fingers for a baby) and push about one third of the chest depth.",
            "Keep going until help arrives, the person starts breathing, or you are too exhausted to continue. Swap with someone every 2 minutes if you can.",
            "If they start breathing: roll them onto their side (recovery position), keep them warm and watch their breathing.",
        ],
        "dont": ["Don't try to press water out of the stomach; it wastes time.",
                 "Don't stop CPR to check for a pulse every few seconds.",
                 "Don't leave the person alone, even if they seem to recover. Water in the lungs can cause problems hours later."],
        "get_help": ["Everyone rescued from drowning must see a doctor, even if they feel fine.",
                     "Cough, breathlessness, chest pain or drowsiness in the next 24 hours: go to hospital."],
        "follow_up": ["Recovery position", "Child not breathing", "Cold after rescue"],
    },
    {
        "id": "bleeding", "urgency": "urgent", "call": ["108"],
        "keywords": ["bleed", "bleeding", "cut", "wound", "gash", "injury", "khoon", "chot", "ghav", "जखम", "खून", "चोट", "रक्त", "घाव"],
        "title": "Cuts and bleeding",
        "summary": "Firm, steady pressure stops most bleeding. Floodwater is dirty, so every wound needs cleaning and watching.",
        "steps": [
            "Protect your hands if you can (gloves, a plastic bag).",
            "Press firmly on the wound with a clean cloth or pad. Keep pressing for 10 full minutes without lifting to check.",
            "If blood soaks through, put another cloth on top and keep pressing. Don't remove the first one.",
            "Raise the injured arm or leg above heart level while pressing.",
            "Once it stops, clean around the wound with boiled-and-cooled or bottled water and soap. Never use floodwater.",
            "Cover with a clean, dry dressing. Change it daily or when wet or dirty.",
            "If the wound touched floodwater, soil or rusty metal: ask about a tetanus injection (if the last one was more than 5 years ago).",
            "Life-threatening bleeding from an arm or leg that pressure can't stop: tie a tight band 5 to 7 cm above the wound, note the time, and get to hospital now.",
        ],
        "dont": ["Don't pull out objects stuck in the wound; pad around them.",
                 "Don't put turmeric, ash, coffee powder or mud on the wound.",
                 "Don't close a dirty wound tightly with tape."],
        "get_help": ["Bleeding that won't stop after 10 minutes of pressure.",
                     "Deep or gaping wounds, wounds on the face, or bites.",
                     "Redness spreading, swelling, pus, fever or red streaks in the days after: signs of infection."],
        "follow_up": ["Wound infection signs", "Tetanus injection", "Broken bone"],
    },
    {
        "id": "snake", "urgency": "emergency", "call": ["108", "112"],
        "keywords": ["snake", "saanp", "saap", "saamp", "cobra", "krait", "viper", "bite by", "साप", "सांप", "साँप", "सर्पदंश"],
        "title": "Snake bite",
        "summary": "Snakes move to dry ground during floods. Antivenom at a hospital is the only real treatment, so travel there quickly and calmly.",
        "steps": [
            "Move the person away from the snake. Don't try to catch or kill it; a photo from a safe distance helps doctors.",
            "Keep the person calm and lying still. Movement spreads venom faster.",
            "Remove rings, watches, bangles, anklets and tight clothing near the bite before swelling starts.",
            "Keep the bitten limb still, like a fracture, using a splint or sling, at or slightly below heart level.",
            "Call 108 and go to the nearest hospital that has antivenom (most district and PHC hospitals do). Carry the person if possible.",
            "Note the time of the bite and any symptoms: pain, swelling, drooping eyelids, trouble swallowing or breathing, bleeding gums.",
            "Krait bites may not hurt and are often at night while sleeping on the floor. Any unexplained weakness after sleeping on the floor: treat as a snake bite.",
            "If breathing stops, start CPR.",
        ],
        "dont": ["Don't cut the wound, suck out venom, or apply ice, chemicals or electric shock.",
                 "Don't tie a tight tourniquet.",
                 "Don't waste time on traditional healers; antivenom works best early.",
                 "Don't give alcohol or painkillers like aspirin."],
        "get_help": ["Every snake bite needs a hospital visit, even if it looks harmless. Symptoms can appear hours later."],
        "follow_up": ["Not breathing / CPR", "Preventing snake bites", "Dog or animal bite"],
    },
    {
        "id": "electric", "urgency": "emergency", "call": ["108", "112"],
        "keywords": ["electric", "current", "shock", "wire", "bijli", "karant", "live wire", "करंट", "बिजली", "वीज", "शॉक"],
        "title": "Electric shock",
        "summary": "Floodwater conducts electricity. Make sure the current is off before you touch anyone.",
        "steps": [
            "Don't touch the person while they may still be in contact with electricity or standing in electrified water.",
            "Switch off the power at the mains or meter if you can reach it without stepping in water.",
            "If you can't switch it off, push the wire away with something dry and non-metal (a dry wooden stick or plastic chair) while standing on something dry.",
            "Call 108 or 112. Report fallen power lines to the electricity board.",
            "Once safe, check breathing. If not breathing normally, start CPR.",
            "Cool burns under clean running water for 20 minutes and cover loosely with cling film or a clean cloth.",
            "Keep the person lying down and warm; they may be in shock (pale, cold, fast pulse).",
        ],
        "dont": ["Don't walk through water near fallen wires or submerged sockets.",
                 "Don't switch appliances back on until an electrician checks them after the flood."],
        "get_help": ["Everyone who had a significant shock needs a hospital check: it can disturb the heart rhythm hours later."],
        "follow_up": ["Not breathing / CPR", "Burns", "Returning home safely"],
    },
    {
        "id": "water", "urgency": "care", "call": [],
        "keywords": ["water", "drink", "diarrhea", "diarrhoea", "loose motion", "vomit", "vomiting", "cholera", "typhoid", "dysentery",
                     "stomach", "paani", "dast", "ulti", "पानी", "पाणी", "दस्त", "उल्टी", "जुलाब", "ors", "dehydration"],
        "title": "Safe water, diarrhoea and dehydration",
        "summary": "Most illness after floods comes from dirty water. Make water safe, and replace lost fluids early with ORS.",
        "steps": [
            "Drink only water that is boiled (rolling boil for at least 1 minute), bottled, or chlorinated.",
            "Chlorine tablets: follow the pack (usually 1 tablet per 20 litres, wait 30 minutes). Household bleach (5%): 2 drops per litre of clear water, wait 30 minutes.",
            "Cloudy water: let it settle or filter through a clean cloth first, then boil or chlorinate.",
            "For diarrhoea, start ORS at the first loose stool: 1 packet in 1 litre of safe water. Sip often.",
            "No ORS packet? Mix 6 level teaspoons of sugar and half a level teaspoon of salt in 1 litre of safe water.",
            "Children: give ORS after every loose stool (about half a cup under 2 years, a cup for older children) and continue breastfeeding and food.",
            "Children with diarrhoea should also get zinc tablets for 14 days (from a health worker or pharmacy).",
            "Keep eating light, cooked food: rice, dal, khichdi, bananas, curd.",
            "Wash hands with soap before cooking, eating and feeding children, and after using the toilet.",
        ],
        "dont": ["Don't drink floodwater or water from wells that were flooded until they are disinfected.",
                 "Don't give anti-diarrhoea medicines to young children.",
                 "Don't stop feeding or breastfeeding."],
        "get_help": ["Blood in stool, high fever, or vomiting that stops all fluids.",
                     "Very little or no urine, sunken eyes, very dry mouth, drowsiness: dehydration.",
                     "Babies, elderly people and pregnant women with diarrhoea should be seen early.",
                     "Watery diarrhoea like rice water with fast dehydration: possible cholera, go to hospital now."],
        "follow_up": ["Fever after flood", "Food safety", "Child with fever"],
    },
    {
        "id": "lepto", "urgency": "urgent", "call": ["108"],
        "keywords": ["fever", "leptospirosis", "lepto", "rat fever", "body pain", "muscle pain", "bukhar", "taap", "jwar", "बुखार", "ताप", "ज्वर"],
        "title": "Fever after a flood (leptospirosis and others)",
        "summary": "Fever in the 2 to 20 days after wading in floodwater can be leptospirosis, dengue, malaria or typhoid. All are treatable if tested early.",
        "steps": [
            "Tell the doctor you walked or worked in floodwater. That changes which tests and medicines they choose.",
            "Get tested early (within 1 to 2 days of fever) at a government health centre; tests and treatment are usually free.",
            "Leptospirosis signs: sudden fever, severe calf muscle pain, red eyes, headache. It spreads through cuts and eyes touching water contaminated by rat urine.",
            "Doctors often give preventive doxycycline to people heavily exposed to floodwater. Ask at the health camp.",
            "Rest, drink plenty of safe fluids, and take paracetamol for fever (adult: 500 mg to 1 g every 6 hours, no more than 4 g a day).",
            "Sponge with lukewarm water if the fever is very high.",
        ],
        "dont": ["Don't take ibuprofen, diclofenac or aspirin for fever until dengue is ruled out: they can cause bleeding.",
                 "Don't take leftover antibiotics without a doctor."],
        "get_help": ["Yellow eyes or skin, very little urine, breathlessness, bleeding, confusion: go to hospital now.",
                     "Any fever in a child under 3 months, or fever lasting more than 2 days."],
        "follow_up": ["Dengue and malaria", "Wound infection signs", "Safe drinking water"],
    },
    {
        "id": "mosquito", "urgency": "care", "call": [],
        "keywords": ["mosquito", "dengue", "malaria", "chikungunya", "machhar", "मच्छर", "डास", "डेंगू", "मलेरिया"],
        "title": "Dengue, malaria and mosquitoes",
        "summary": "Standing water after floods breeds mosquitoes within a week. Prevent bites and get fever tested early.",
        "steps": [
            "Empty or cover anything holding water around your home and camp: buckets, tyres, pots, coolers, coconut shells.",
            "Sleep under a mosquito net (insecticide-treated if available), especially children and pregnant women.",
            "Wear long sleeves and trousers at dawn and dusk; use repellent on exposed skin.",
            "Fever with severe body ache, pain behind the eyes or rash: get a dengue test. Fever with chills and sweating in cycles: get a malaria test.",
            "For dengue: drink plenty of fluids (ORS, coconut water, soups) and take only paracetamol for fever.",
        ],
        "dont": ["Don't take painkillers like ibuprofen or aspirin if dengue is possible."],
        "get_help": ["Warning signs of severe dengue, usually as the fever falls: severe stomach pain, repeated vomiting, bleeding gums or nose, black stools, restlessness or drowsiness. Go to hospital immediately."],
        "follow_up": ["Fever after flood", "Child with fever"],
    },
    {
        "id": "cold", "urgency": "urgent", "call": ["108"],
        "keywords": ["cold", "shiver", "shivering", "hypothermia", "freezing", "wet clothes", "thand", "ठंड", "थंडी", "कांपना"],
        "title": "Cold and wet (hypothermia)",
        "summary": "Hours in floodwater or rain can dangerously cool the body, even in a warm climate. Warm people slowly and gently.",
        "steps": [
            "Move the person to a dry, sheltered place out of the wind.",
            "Remove wet clothes gently and dry the skin.",
            "Wrap them in dry blankets or clothes, covering the head and neck. Put a layer underneath them too; the ground takes heat away.",
            "Share body heat: skin-to-skin contact under a blanket works well for children.",
            "If fully awake and able to swallow, give warm sweet drinks (tea, milk, jaggery water).",
            "Keep them lying down and handle them gently.",
        ],
        "dont": ["Don't rub or massage the arms and legs.",
                 "Don't use very hot water, fire or heaters directly on the skin.",
                 "Don't give alcohol."],
        "get_help": ["Confusion, slurred speech, extreme drowsiness, or when shivering stops while still cold: call 108. These are signs of severe hypothermia."],
        "follow_up": ["Not breathing / CPR", "Emergency kit"],
    },
    {
        "id": "fracture", "urgency": "urgent", "call": ["108"],
        "keywords": ["fracture", "broken", "bone", "sprain", "twist", "swollen", "dislocate", "haddi", "moch", "हड्डी", "फ्रैक्चर", "मोच", "हाड"],
        "title": "Broken bones and sprains",
        "summary": "Keep the injured part still. Movement causes pain and more damage.",
        "steps": [
            "Don't try to straighten the limb. Support it in the position you found it.",
            "Make a splint: pad the limb, then tie it gently to something rigid (a stick, rolled newspaper, cardboard) that covers the joint above and below.",
            "For an arm, use a sling made from a scarf or dupatta.",
            "Apply a cold pack wrapped in cloth for 15 to 20 minutes to reduce swelling (not ice directly on skin).",
            "Check fingers or toes below the injury: they should stay warm, pink, and able to move. Loosen ties if they turn cold, blue or numb.",
            "Bone sticking through the skin: cover it with a clean dressing, don't push it back, and go to hospital now.",
            "Suspected neck or back injury (after a fall or being hit by debris): don't move the person unless they are in danger; call 108.",
        ],
        "dont": ["Don't let the person walk on a possibly broken leg.",
                 "Don't massage or apply hot oil."],
        "get_help": ["Deformity, severe pain, can't bear weight, numbness, or any open wound over a fracture."],
        "follow_up": ["Cuts and bleeding", "Carrying an injured person"],
    },
    {
        "id": "burns", "urgency": "urgent", "call": ["108"],
        "keywords": ["burn", "burnt", "scald", "fire", "hot water", "jal gaya", "जलना", "भाजले", "जला"],
        "title": "Burns and scalds",
        "summary": "Cool the burn with clean water for 20 minutes. It is the single best treatment.",
        "steps": [
            "Stop the burning: move away from the heat; smother flames with a blanket (stop, drop and roll).",
            "Cool the burn under cool, clean running water for 20 minutes. It still helps up to 3 hours after the burn.",
            "Remove rings, bangles and clothing near the burn unless stuck to the skin.",
            "Cover loosely with cling film or a clean, non-fluffy cloth.",
            "Keep the rest of the person warm; large burns cause shock.",
            "Paracetamol can help with pain.",
        ],
        "dont": ["Don't put toothpaste, ghee, oil, butter, turmeric or ice on a burn.",
                 "Don't burst blisters."],
        "get_help": ["Burns larger than the person's palm, on the face, hands, feet, genitals or joints, deep or white/charred burns, electrical or chemical burns, and any burn in a child or elderly person."],
        "follow_up": ["Electric shock", "Wound infection signs"],
    },
    {
        "id": "skin", "urgency": "care", "call": [],
        "keywords": ["infection", "pus", "rash", "itch", "itching", "fungal", "skin", "foot", "feet", "khujli", "खुजली", "संक्रमण", "पस", "tetanus"],
        "title": "Skin, feet and wound infections",
        "summary": "Long hours in wet conditions cause fungal infections, 'immersion foot' and infected wounds. Keeping skin clean and dry prevents most of it.",
        "steps": [
            "After being in floodwater, wash with soap and clean water and dry thoroughly, especially between the toes.",
            "Change into dry socks and clothes as often as you can; let feet air-dry at night.",
            "Itchy, ring-shaped rashes or white soggy skin between the toes: keep dry and use an antifungal cream (clotrimazole) from a pharmacy.",
            "Check every cut and scratch daily. Clean and cover it.",
            "Infection signs: increasing redness, warmth, swelling, pus, pain, or red lines spreading from the wound.",
            "Tetanus: if you have a wound and haven't had a tetanus injection in the last 5 years, get one at a health centre.",
        ],
        "dont": ["Don't walk barefoot in floodwater or mud; nails, glass and snakes hide below."],
        "get_help": ["Infection signs with fever, spreading redness, or a wound that doesn't improve in 2 days.",
                     "Jaw stiffness or muscle spasms days after a wound: possible tetanus, go to hospital now."],
        "follow_up": ["Cuts and bleeding", "Fever after flood"],
    },
    {
        "id": "heart", "urgency": "emergency", "call": ["108", "112"],
        "keywords": ["chest pain", "heart", "heart attack", "stroke", "paralysis", "face drooping", "slurred", "seene me dard", "दिल", "छाती", "सीने", "लकवा", "छातीत"],
        "title": "Chest pain, heart attack or stroke",
        "summary": "Stress, exertion and missed medicines during floods trigger heart attacks and strokes. Fast hospital treatment saves lives and brain.",
        "steps": [
            "Heart attack signs: chest pain or pressure (may spread to the arm, jaw or back), sweating, breathlessness, nausea. Women and diabetics may only feel tired or breathless.",
            "Call 108 right away. Sit the person down, half-sitting, and loosen tight clothing.",
            "If they are not allergic and not bleeding, give one 300 mg aspirin to chew (not swallow whole).",
            "Stroke signs (BE FAST): Balance lost, Eyes blurred, Face drooping, Arm weak, Speech slurred, Time to call 108.",
            "Note the time symptoms started. Stroke treatment works only within a few hours.",
            "If they collapse and stop breathing normally, start CPR.",
        ],
        "dont": ["Don't give aspirin for a suspected stroke (it may be bleeding in the brain).",
                 "Don't let them walk or exert themselves.",
                 "Don't give food or drink to someone with stroke signs; swallowing may be affected."],
        "get_help": ["These are always emergencies. Call 108 immediately."],
        "follow_up": ["Not breathing / CPR", "Medicines during evacuation"],
    },
    {
        "id": "breathing", "urgency": "urgent", "call": ["108"],
        "keywords": ["breath", "breathing difficulty", "breathless", "asthma", "wheeze", "inhaler", "cough", "saans phoolna", "दमा", "सांस फूल", "धाप"],
        "title": "Breathing difficulty and asthma",
        "summary": "Damp, mould, smoke and stress trigger asthma. Act early and keep inhalers close.",
        "steps": [
            "Sit the person upright, leaning slightly forward. Keep them calm; breathe slowly with them.",
            "Asthma: use the reliever inhaler (usually blue, salbutamol) — 1 puff every 30 to 60 seconds, up to 10 puffs, with a spacer if available.",
            "If no better after 10 puffs, call 108 and repeat the puffs while waiting.",
            "Move away from smoke, dust and mould. Don't run generators or charcoal stoves indoors: they produce carbon monoxide.",
            "Headache, dizziness and nausea in several people in a closed room with a generator or stove: get everyone into fresh air now (carbon monoxide).",
        ],
        "dont": ["Don't lie the person flat.", "Don't leave inhalers behind when evacuating."],
        "get_help": ["Blue lips, can't speak in full sentences, exhaustion, or drowsiness: call 108 now."],
        "follow_up": ["Medicines during evacuation", "Returning home safely"],
    },
    {
        "id": "meds", "urgency": "care", "call": [],
        "keywords": ["medicine", "medicines", "insulin", "diabetes", "sugar", "bp", "blood pressure", "dialysis", "tablet", "dawai", "दवा", "दवाई", "औषध", "शुगर"],
        "title": "Medicines and long-term conditions during evacuation",
        "summary": "Missing regular medicines is one of the biggest hidden dangers in a disaster. Carry them and a written list.",
        "steps": [
            "Pack at least 7 days of all regular medicines in a waterproof bag, with a written list of names and doses.",
            "Insulin: keep it cool (in a clay pot or a cloth kept damp, out of direct sun). Unopened insulin stays usable for about 4 weeks at room temperature.",
            "Diabetes: eat regularly even if food is limited. Low sugar signs (shaking, sweating, confusion): give sugar, glucose, jaggery or a sweet drink right away.",
            "Blood pressure, heart, epilepsy, TB, HIV and mental-health medicines must not be stopped suddenly.",
            "Dialysis patients: tell the relief camp staff on arrival so they arrange transport to a dialysis centre.",
            "Lost your medicines? Tell the health camp: government camps provide essential medicines free.",
        ],
        "dont": ["Don't use medicines that got wet in floodwater (tablets, syrups, eye drops); replace them.",
                 "Don't double doses to 'catch up' without advice."],
        "get_help": ["Very high or very low sugar that doesn't settle, fits, or chest pain: call 108."],
        "follow_up": ["Emergency kit", "Pregnancy and newborns"],
    },
    {
        "id": "pregnancy", "urgency": "urgent", "call": ["108", "102"],
        "keywords": ["pregnant", "pregnancy", "labour", "delivery", "baby", "newborn", "infant", "breastfeed", "garbhvati", "गर्भवती", "प्रसूति", "बच्चा", "बाळ", "नवजात"],
        "title": "Pregnancy, newborns and young children",
        "summary": "Pregnant women and babies are most at risk. Evacuate them early and keep them warm, fed and away from floodwater.",
        "steps": [
            "Evacuate pregnant women, new mothers and babies first. Call 102 or 108 for free maternity transport.",
            "Carry the pregnancy record (MCP card), any medicines (iron, calcium) and clean clothes and cloths for the baby.",
            "Keep breastfeeding: it protects babies from infections and dehydration. Stress doesn't stop milk.",
            "Keep babies warm and dry, skin-to-skin with the mother if cold.",
            "Use only safe water for any formula and boil bottles, or feed with a clean cup.",
            "Wash hands before handling the baby.",
        ],
        "dont": ["Don't let children play in floodwater.",
                 "Don't give newborns water, honey or other liquids besides breast milk."],
        "get_help": ["In pregnancy: bleeding, leaking water, severe headache or blurred vision, fits, severe stomach pain, or the baby moving less. Call 102 or 108.",
                     "Baby: not feeding, very sleepy, fast breathing, fever or feeling cold, yellow skin, or fits."],
        "follow_up": ["Child with fever", "Safe drinking water"],
    },
    {
        "id": "child_fever", "urgency": "urgent", "call": ["108"],
        "keywords": ["child fever", "kid", "child", "children", "baccha", "बच्चे", "मुलगा", "मूल"],
        "title": "Sick children",
        "summary": "Children get dehydrated and ill fast after floods. Watch for danger signs.",
        "steps": [
            "Give plenty of fluids: breast milk, ORS, safe water. Keep feeding.",
            "Fever: paracetamol syrup by weight (about 15 mg per kg, every 6 hours, maximum 4 doses a day). Check the bottle strength.",
            "Sponge with lukewarm water; dress lightly.",
            "Protect from mosquitoes with a net, and from floodwater.",
        ],
        "dont": ["Don't give aspirin to children.", "Don't wrap a feverish child in heavy blankets."],
        "get_help": ["Danger signs: can't drink or breastfeed, vomits everything, fits, very sleepy or hard to wake, fast or difficult breathing, fever over 2 days, or any fever under 3 months of age. Go to hospital now."],
        "follow_up": ["Safe drinking water", "Dengue and malaria"],
    },
    {
        "id": "animal", "urgency": "urgent", "call": ["108"],
        "keywords": ["dog bite", "dog", "rabies", "animal bite", "rat bite", "monkey", "kutta", "कुत्ता", "कुत्रा", "रेबीज"],
        "title": "Dog or animal bites (rabies)",
        "summary": "Rabies is 100% fatal once symptoms start, and 100% preventable with prompt vaccination.",
        "steps": [
            "Wash the wound immediately with soap and running water for 15 minutes. This alone greatly lowers rabies risk.",
            "Apply an antiseptic (povidone-iodine) if available.",
            "Go to a government hospital or health centre the same day for anti-rabies vaccine (free). Deep bites may also need immunoglobulin.",
            "Complete all vaccine doses on the dates given (days 0, 3, 7 and 28).",
        ],
        "dont": ["Don't stitch or tightly bandage the bite.", "Don't apply chilli, oil or herbs."],
        "get_help": ["Every bite or scratch that breaks the skin from a dog, cat, monkey or other mammal needs vaccination advice."],
        "follow_up": ["Cuts and bleeding", "Snake bite"],
    },
    {
        "id": "mental", "urgency": "care", "call": ["14416"],
        "keywords": ["stress", "anxiety", "panic", "fear", "scared", "sleep", "cant sleep", "depressed", "sad", "trauma", "tension", "darr", "डर", "तनाव", "भीती", "घबराहट"],
        "title": "Stress, fear and panic",
        "summary": "Feeling scared, numb, angry or unable to sleep after a disaster is a normal reaction. Most people feel better with support and time.",
        "steps": [
            "Panic attack: breathe slowly — in through the nose for 4 counts, hold for 2, out through the mouth for 6. Repeat for a few minutes.",
            "Ground yourself: name 5 things you see, 4 you can touch, 3 you hear.",
            "Stay with family or neighbours; talk about what happened when you're ready.",
            "Keep small routines: regular meals, sleep times, prayers, helping others at the camp.",
            "Children: stay close, explain simply and honestly, let them play, and limit their exposure to frightening news.",
            "Free, confidential support: Tele-MANAS 14416 or 1-800-891-4416 (24x7, many languages).",
        ],
        "dont": ["Don't use alcohol or sleeping pills to cope.", "Don't force anyone to talk before they're ready."],
        "get_help": ["Thoughts of self-harm or suicide, not eating or sleeping for days, or not recognising people: call 14416 or 112 now."],
        "follow_up": ["Sick children", "Emergency kit"],
    },
    {
        "id": "kit", "urgency": "care", "call": [],
        "keywords": ["kit", "pack", "bag", "carry", "prepare", "ready", "saman", "सामान", "तयारी", "बॅग"],
        "title": "Emergency kit to carry",
        "summary": "Pack a bag now so you can leave within minutes of a warning.",
        "steps": [
            "Water: 3 litres per person per day for 2 to 3 days, plus water purification tablets.",
            "Dry food: chiwda, biscuits, roasted chana, jaggery, dry fruits; baby food if needed.",
            "Medicines for 7 days with a written list; first-aid kit with bandages, antiseptic, ORS, paracetamol, gloves.",
            "Torch, spare batteries, charged phone and power bank; a whistle to signal for help.",
            "Aadhaar, ration card, bank passbook, insurance and property papers in a sealed plastic bag (and photos on your phone).",
            "Cash in small notes, a change of clothes, a blanket or mat, sanitary pads, soap, masks.",
            "Write important phone numbers on paper in case your phone dies.",
        ],
        "dont": ["Don't go back for belongings once you've been told to leave."],
        "get_help": [],
        "follow_up": ["Evacuating safely", "Medicines during evacuation"],
    },
    {
        "id": "evacuate", "urgency": "care", "call": ["112"],
        "keywords": ["evacuate", "leave", "escape", "route", "shelter", "camp", "trapped", "stuck", "rescue", "nikal", "निकल", "बाहेर", "फंसे", "अडकलो"],
        "title": "Evacuating safely",
        "summary": "Leave early, on foot if roads are flooding, and never cross moving water.",
        "steps": [
            "Follow the route in the Evacuate tab: it avoids roads that flood before you reach them.",
            "Switch off electricity and gas at the mains before leaving, if it is safe.",
            "Never walk through moving water: 15 cm can knock you down. Never drive through it: 60 cm floats a car.",
            "Use a stick to test the ground ahead; manhole covers may be open.",
            "Help elderly people, children, pregnant women and people with disabilities first.",
            "Trapped by rising water: go to the highest floor or the roof (not a closed attic), take water, a torch and a phone, and call 112. Wave a bright cloth or use a torch to signal.",
            "Tell relatives where you're going. Register at the relief camp so people can find you.",
        ],
        "dont": ["Don't stay near riverbanks, bridges, or under trees and power lines.",
                 "Don't go back home until officials say it is safe."],
        "get_help": ["Trapped, injured, or someone missing: call 112."],
        "follow_up": ["Emergency kit", "Returning home safely"],
    },
    {
        "id": "return", "urgency": "care", "call": [],
        "keywords": ["return", "go back", "going home", "clean", "cleaning", "mould", "mold", "generator", "carbon monoxide", "ghar wapas", "सफाई", "घर लौट", "घरी परत"],
        "title": "Returning home and cleaning up",
        "summary": "Many injuries happen after the water goes down. Check the house is safe before you go in.",
        "steps": [
            "Return only when authorities say it is safe. Go in daylight.",
            "Check for cracks, sagging roofs or leaning walls before entering. If you smell gas, leave and call the gas agency.",
            "Keep the main switch off until an electrician checks the wiring and appliances.",
            "Wear boots, gloves and a mask while cleaning. Watch for snakes and scorpions hiding in dark corners.",
            "Throw away food, medicines and cosmetics that touched floodwater, and anything in dented or swollen cans.",
            "Clean surfaces with soap and water, then disinfect with 1 cup of household bleach in 20 litres of water. Open windows while you work.",
            "Dry the house fully and remove soaked mattresses and carpets to prevent mould.",
            "Disinfect wells before use: ask the gram panchayat or health worker for bleaching powder and the right dose.",
        ],
        "dont": ["Never run a generator, charcoal stove or kerosene heater indoors or in a closed space: carbon monoxide kills without warning.",
                 "Don't let children play in debris or floodwater puddles."],
        "get_help": ["Headache, dizziness and nausea in several people in the same room: get to fresh air and call 108 (carbon monoxide)."],
        "follow_up": ["Safe drinking water", "Skin, feet and wound infections"],
    },
    {
        "id": "recovery", "urgency": "care", "call": [],
        "keywords": ["recovery position", "side position", "unconscious breathing"],
        "title": "Recovery position",
        "summary": "Use this for someone who is unconscious but breathing normally, so they don't choke.",
        "steps": [
            "Kneel beside them. Place the arm nearest you at a right angle, palm up.",
            "Bring the far arm across the chest and hold the back of their hand against their near cheek.",
            "Bend the far knee up, then pull on that knee to roll them towards you onto their side.",
            "Tilt the head back slightly so the airway stays open and fluid can drain from the mouth.",
            "Keep checking their breathing until help arrives. If it stops, roll them back and start CPR.",
        ],
        "dont": ["Don't use this position if you suspect a neck or back injury, unless they are vomiting or you must leave them."],
        "get_help": ["Anyone unconscious needs an ambulance: call 108."],
        "follow_up": ["Not breathing / CPR"],
    },
]

QUICK_REPLIES = ["Drowning / CPR", "Bleeding", "Snake bite", "Electric shock", "Fever after flood",
                 "Diarrhoea / ORS", "Emergency kit", "Stress and panic"]
ALIASES = {  # quick-reply and follow-up labels -> topic id
    "drowning / cpr": "cpr", "not breathing / cpr": "cpr", "child not breathing": "cpr", "recovery position": "recovery",
    "bleeding": "bleeding", "cuts and bleeding": "bleeding", "snake bite": "snake", "preventing snake bites": "snake",
    "electric shock": "electric", "fever after flood": "lepto", "diarrhoea / ors": "water", "safe drinking water": "water",
    "food safety": "return", "emergency kit": "kit", "stress and panic": "mental", "cold after rescue": "cold",
    "wound infection signs": "skin", "tetanus injection": "skin", "broken bone": "fracture", "carrying an injured person": "fracture",
    "burns": "burns", "returning home safely": "return", "dengue and malaria": "mosquito", "child with fever": "child_fever",
    "sick children": "child_fever", "medicines during evacuation": "meds", "pregnancy and newborns": "pregnancy",
    "evacuating safely": "evacuate", "dog or animal bite": "animal", "skin, feet and wound infections": "skin",
}
GREETING = re.compile(r"^\s*(hi|hello|hey|namaste|namaskar|नमस्ते|नमस्कार|help|start)\b", re.I)
URGENCY_LABEL = {"emergency": "Emergency: call now", "urgent": "See a doctor today", "care": "Self-care: watch for warning signs"}


def _score(topic, text):
    score = 0
    for k in topic["keywords"]:
        if k in text:
            score += 2 if " " in k else 1  # multi-word phrases are more specific
    return score


def reply(message: str, lang: str = "en") -> dict:
    text = (message or "").lower().strip()
    best = None
    if text in ALIASES:
        best = next(t for t in TOPICS if t["id"] == ALIASES[text])
    elif text and not GREETING.match(text):
        scored = sorted(((_score(t, text), t) for t in TOPICS), key=lambda x: -x[0])
        if scored[0][0] > 0:
            best = scored[0][1]
            # Life-threatening topics win ties.
            ties = [t for s, t in scored if s == scored[0][0]]
            best = next((t for t in ties if t["urgency"] == "emergency"), best)

    if best is None:
        return {
            "intent": "fallback",
            "title": "How can I help?",
            "text": "I can guide you through first aid and staying healthy during and after a flood. "
                    "Describe what happened in a few words (for example 'snake bite on leg' or "
                    "'child has fever and loose motions'), or tap a topic below.",
            "steps": [], "dont": [], "get_help": [], "urgency": None, "call": ["108", "112"],
            "disclaimer": DISCLAIMER, "quick_replies": QUICK_REPLIES, "engine": "scripted",
        }
    return {
        "intent": best["id"],
        "title": best["title"],
        "text": best["summary"],
        "urgency": best["urgency"],
        "urgency_label": URGENCY_LABEL[best["urgency"]],
        "call": best["call"],
        "steps": best["steps"],
        "dont": best["dont"],
        "get_help": best["get_help"],
        "disclaimer": DISCLAIMER,
        "quick_replies": best["follow_up"] + [q for q in QUICK_REPLIES if q not in best["follow_up"]][:3],
        "engine": "scripted",
    }
